### PR TITLE
[Update use-upload-files.tsx] [Bug fix] Added an 'id' field in files[]

### LINKED ISSUE #150: Can a unique Id field be added to the 'files' array??
@ryanto So I had a requirement to show the file names (along with a loader) until the upload process finishes. I used the 'files' array to achieve this task.

But the problem occurred when I had to assign a 'key' to each file item. Initially I used the file name as key... but it can happen that 2 files, which are being uploaded, have the same key and thus react giving us error that 'encountered same key'.

Now using index as key would be problematic (as if a file's upload is complete earlier than other... it would violate the rule that keys must be 'unique' amongst sibling)

And generating a unique Id for each file [using lets say uuid()] would mean that the keys would change every-time user adds a new file or when the component re-renders.

So is there a way by which 'files' array can have a unique uuid() for each file **which is persisted while the file finishes its upload**??

### PR DESCRIPTION
**Pull request by nik32**
[closes #150] This field should be used as 'key' if we are to avoid a subtle bug (know more in the issue linked to this PR)

In the PR especially review -
1. Is it okay to use absolute imports (used to import uuid() from /utils) or you want only relative import

Guide me as to -
1. How to update the docs to reflect this change
2. How to update TS definition of TrackedFile in use-s3-upload.d.ts 
[as 1) we need to reflect this new id 'field' there also + 2) I would like to export that TrackedFile for it being available to our package users]

### CODE REVIEW

**Comment by ryanto** [comment]
Awesome job @nik32 thanks for doing this! Only one small comment on the PR.

To answer your questions:

1. Let's get your code merged in and released then we can circle back and do the docs. That way you can start using this before docs get written.

2. Looks like you updated the type, it looks good 👍 . I'd love to hear more about why you need the type exported. I believe you can rely on TS inference to use this type:

```
let { files } = useS3Upload();
// files will be TrackedFile[]
```

File: packages/next-s3-upload/src/hooks/use-upload-files.tsx [hunk 1]
```diff
@@ -1,12 +1,14 @@
 import React from 'react';
 import { FileInput } from '../components/file-input';
 import { useRef, useState } from 'react';
+import { uuid } from 'next-s3-upload/src/utils/keys';
```
Comment (ryanto) [inline packages/next-s3-upload/src/hooks/use-upload-files.tsx:4]: Let's do relative import since I believe the rest of the code is doing this. Absolute might be fine but let's do relative to keep things consistent.

**Comment by ryanto** [comment]
For docs you add `id` to this table: I think that's enough to communicate the new feature: https://github.com/ryanto/next-s3-upload/blob/master/packages/docs-site/src/pages/use-s3-upload.mdx#L57

File: packages/next-s3-upload/src/hooks/use-upload-files.tsx (hunk 1 above)
Comment (nik32) [reply packages/next-s3-upload/src/hooks/use-upload-files.tsx:4]: Got it

**Comment by nik32** [comment]
> 2\. Looks like you updated the type, it looks good 👍. I'd love to hear more about why you need the type exported. I believe you can rely on TS inference to use this type:


@ryanto 

1. Regarding why I wanted the type exported - I have passed files[] as props to child component. Now in the props type definitions it gives error coz the type is not exported.
image
2. Also, I updated the TrackedFile type in "use-upload-files.tsx"... but there is another TrackedFile file in "use-upload-files.d.ts" (which I found in locally installed package code but not in the git repo. And I think these are the TS definitions available to our package consumers). So don't we have to add the 'id' field there?

**Comment by nik32** [comment]
@ryanto are you satisfied with my above answer?

**Comment by ryanto** [comment]
Thanks again for doing this @nik32 ! It's published as version `0.3.2` :)

**Comment by ryanto** [comment]
For the types you can use 

```
import { useS3Upload } from "next-s3-upload";

type MyFile = ReturnType<typeof useS3Upload>['files'][number]
```

I'll eventually get a type exported for you, but the above code should help you get unstuck today.

**Comment by nik32** [comment]
Thanks @ryanto for integrating this! I have integrated it and its working fine.
